--2pg132
SELECT*
FROM ORDERS

--4pg132
SELECT ORDER_NUM
FROM ORDERS
	WHERE CUSTOMER_NUM = '608'
	AND ORDER_DATE = '10/23/2010'
	
--6pg132
SELECT PART_NUM, DESCRIPTION
FROM PART 
	WHERE not class = 'AP'

--8pg132
SELECT PART_NUM, DESCRIPTION,ON_HAND_VALUE  = (ON_HAND * PRICE)
FROM PART
	WHERE CLASS = 'SG'
	
--10pg132
SELECT PART_NUM, DESCRIPTION
FROM PART
	WHERE CLASS = 'AP'
	
--12pg132
SELECT *
FROM PART
	ORDER BY DESCRIPTION ASC
	
--14pg132
SELECT CUSTOMERS_WITH_BALANCE_GREATER_THAN_CREDIT_LIMIT = COUNT(CUSTOMER_NAME)
FROM CUSTOMER
	WHERE BALANCE > CREDIT_LIMIT
	
--16pg132
SELECT PART_NUM, DESCRIPTION, ON_HAND_VALUE  = (ON_HAND * PRICE)
FROM PART
	WHERE ON_HAND > (SELECT AVG(PART.ON_HAND) FROM PART)
 
 --18pg132
 SELECT PART_NUM, DESCRIPTION, PRICE
 FROM PART
	WHERE PRICE = (SELECT MIN(PRICE) FROM PART)

--20pg132
SELECT REP_NUM, SUM(BALANCE)
FROM CUSTOMER
	GROUP BY REP_NUM 
	HAVING SUM(BALANCE) >= 10000


--2pg167
SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME, ORDER_NUM
FROM  CUSTOMER
LEFT JOIN ORDERS
ON CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM
WHERE ORDER_DATE = '10/23/2010'

--4pg167
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM CUSTOMER
WHERE CUSTOMER_NUM IN (SELECT CUSTOMER_NUM
FROM ORDERS WHERE ORDER_DATE = '10/23/2010')

--6pg167
SELECT CUSTOMER_NUM, CUSTOMER_NAME
FROM CUSTOMER
WHERE CUSTOMER_NUM IN (SELECT CUSTOMER_NUM
FROM ORDERS WHERE ORDER_DATE != '10/23/2010')

--8pg167
SELECT ORDERS.ORDER_NUM, ORDERS.ORDER_DATE, ORDER_LINE.PART_NUM, PART.DESCRIPTION, PART.CLASS
FROM ORDERS, ORDER_LINE, PART
WHERE ORDERS.ORDER_NUM = ORDER_LINE.ORDER_NUM
	AND ORDER_LINE.PART_NUM = PART.PART_NUM
ORDER BY CLASS, ORDER_NUM;

--10pg167
SELECT DISTINCT (REP.REP_NUM), REP.LAST_NAME, REP.FIRST_NAME
FROM REP, CUSTOMER
WHERE CUSTOMER.REP_NUM = REP.REP_NUM
AND CUSTOMER.CREDIT_LIMIT = 10000

--12pg167
SELECT PART_NUM, DESCRIPTION, CLASS
FROM PART
ORDER BY CLASS

--14pg167
SELECT ORDER_NUM, ORDER_DATE
FROM ORDERS
WHERE ORDER_NUM IN 
(SELECT ORDER_NUM FROM ORDER_LINE WHERE PART_NUM IN 
(SELECT PART_NUM FROM PART WHERE DESCRIPTION = 'IRON'))

--16pg167
SELECT ORDER_NUM, ORDER_DATE
FROM ORDERS
WHERE ORDER_NUM IN
(SELECT ORDER_NUM FROM ORDER_LINE WHERE PART_NUM IN
(SELECT PART_NUM FROM PART WHERE DESCRIPTION = 'GAS RANGE'))
INTERSECT
SELECT ORDER_NUM, ORDER_DATE
FROM ORDERS
WHERE CUSTOMER_NUM IN
(SELECT CUSTOMER_NUM FROM CUSTOMER WHERE CUSTOMER_NAME = 'Johnson''s Department Store')

--18pg167
SELECT PART_NUM, DESCRIPTION, PRICE, CLASS 
FROM PART
WHERE PRICE > ALL
(SELECT PRICE 
FROM PART
WHERE CLASS ='AP')

--20pg167
SELECT PART.PART_NUM, PART.DESCRIPTION, PART.ON_HAND, ORDER_NUM, NUM_ORDERED
FROM PART
left join ORDER_LINE ON
PART.PART_NUM = ORDER_LINE.PART_NUM
ORDER BY PART_NUM